import { Amplify } from "aws-amplify";
//import { Auth } from "aws-amplify/auth";

 const config = {
  Auth: {
    Cognito: {
      region: "us-east-2", // your AWS region
      userPoolId: "us-east-2_mt5gCCe1c", // your Cognito User Pool ID
      userPoolClientId: "412rtrghbcib07g6rehpbf08vp", // your App Client ID
      loginWith: {
        email: true,
      },
    },
  },
  API: {
    REST: {
      myApi: {
        endpoint: 'https://dn5wcoauce.execute-api.us-east-2.amazonaws.com/dev/v1/auth/login',
        region: "us-east-2",
      },
    },
  },
  API: {
    endpoints: [
      {
        name: "TravelAPI", // logical name
        endpoint: "https://your-api-id.execute-api.ap-south-1.amazonaws.com/dev", // API Gateway endpoint
        region: "ap-south-1",
      },
    ],
   },
   API: {
  endpoints: [
    {
      name: "LGVApi",
      endpoint: "https://your-api-id.execute-api.ap-south-1.amazonaws.com/dev",
      region: "ap-south-1",
    },
  ],
}
};
console.log("Amplify Config Loaded", config);

Amplify.configure(config);
// import { resources } from "./amplify_outputs.json"; // auto-generated by Amplify CLI
// export const amplifyConfig = {
//   API: {
//     TravelAPI: {
//       endpoint: resources.API.TravelAPI.endpoint,
//       region: resources.API.TravelAPI.region,
//     },
//   },
// };